version: '3'

services:
  pb:
    build:
      context: .
      dockerfile: pb.Dockerfile
    ports:
      - "8091:8090"
    volumes:
      - ./pb_migrations:/pocketbase/pb_migrations
      - ./app:/pocketbase/pb_public
      - sca_main_pb_data:/pocketbase/pb_data

volumes:
  sca_main_pb_data:
